name: "Change logger"
description: "Update your changelog with your PR informations"
author: AntonioGally
branding:
  icon: file-text
  color: purple
inputs:
  changelogPath: # id of input
    description: "Relative path to your changelog file"
    required: true
    default: "./CHANGELOG.md"
  commitEmail:
    description: "Email that will be used to commit changes"
    required: true
  commitUserName:
    description: "UserName that will be used to commit changes"
    required: true
  githubToken:
    description: "Github default token"
    required: true

runs:
  using: "node16"
  main: "./dist/index.js"
