name: "Change logger"
description: "Update the changelog by your PR informations"
inputs:
  changelogPath: # id of input
    description: "Path to your changelog file"
    required: true
    default: "./CHANGELOG.md"
  
runs:
  using: "node16"
  main: "./dist/index.js"
